package com.niit.pojo;
// Generated 2020-11-6 19:30:40 by Hibernate Tools 4.3.1



/**
 * JobRequire generated by hbm2java
 */
public class JobRequire  implements java.io.Serializable {


     private int jid;
     private String jname;
     private String rname;
     private String jtype;
     private String jdescriptiont;
     private int jnumber;
     private String jedu;
     private String jexperience;

    public JobRequire() {
    }

	
    public JobRequire(int jid, String jname, String rname, String jdescriptiont, int jnumber, String jedu) {
        this.jid = jid;
        this.jname = jname;
        this.rname = rname;
        this.jdescriptiont = jdescriptiont;
        this.jnumber = jnumber;
        this.jedu = jedu;
    }
    public JobRequire(int jid, String jname, String rname, String jtype, String jdescriptiont, int jnumber, String jedu, String jexperience) {
       this.jid = jid;
       this.jname = jname;
       this.rname = rname;
       this.jtype = jtype;
       this.jdescriptiont = jdescriptiont;
       this.jnumber = jnumber;
       this.jedu = jedu;
       this.jexperience = jexperience;
    }
   
    public int getJid() {
        return this.jid;
    }
    
    public void setJid(int jid) {
        this.jid = jid;
    }
    public String getJname() {
        return this.jname;
    }
    
    public void setJname(String jname) {
        this.jname = jname;
    }
    public String getRname() {
        return this.rname;
    }
    
    public void setRname(String rname) {
        this.rname = rname;
    }
    public String getJtype() {
        return this.jtype;
    }
    
    public void setJtype(String jtype) {
        this.jtype = jtype;
    }
    public String getJdescriptiont() {
        return this.jdescriptiont;
    }
    
    public void setJdescriptiont(String jdescriptiont) {
        this.jdescriptiont = jdescriptiont;
    }
    public int getJnumber() {
        return this.jnumber;
    }
    
    public void setJnumber(int jnumber) {
        this.jnumber = jnumber;
    }
    public String getJedu() {
        return this.jedu;
    }
    
    public void setJedu(String jedu) {
        this.jedu = jedu;
    }
    public String getJexperience() {
        return this.jexperience;
    }
    
    public void setJexperience(String jexperience) {
        this.jexperience = jexperience;
    }




}


