package com.niit.pojo;

import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private String mname;
     private String mtel;
     private String memail;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date mbirth;
     private String mgender;
     private String mpwd;

    public Manager() {
    }

	
    public Manager(String mname, String mtel, String memail, String mpwd) {
        this.mname = mname;
        this.mtel = mtel;
        this.memail = memail;
        this.mpwd = mpwd;
    }
    public Manager(String mname, String mtel, String memail, Date mbirth, String mgender, String mpwd) {
       this.mname = mname;
       this.mtel = mtel;
       this.memail = memail;
       this.mbirth = mbirth;
       this.mgender = mgender;
       this.mpwd = mpwd;
    }
   
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getMtel() {
        return this.mtel;
    }
    
    public void setMtel(String mtel) {
        this.mtel = mtel;
    }
    public String getMemail() {
        return this.memail;
    }
    
    public void setMemail(String memail) {
        this.memail = memail;
    }
    public Date getMbirth() {
        return this.mbirth;
    }
    
    public void setMbirth(Date mbirth) {
        this.mbirth = mbirth;
    }
    public String getMgender() {
        return this.mgender;
    }
    
    public void setMgender(String mgender) {
        this.mgender = mgender;
    }
    public String getMpwd() {
        return this.mpwd;
    }
    
    public void setMpwd(String mpwd) {
        this.mpwd = mpwd;
    }




}


