package com.niit.pojo;
// qm Generated 2020-11-15 19:30:40 by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Recruiter generated by hbm2java
 */
public class Recruiter  implements java.io.Serializable {


     private String rname;
     private String rpic;
     private String rtel;
     private String remail;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date rbirth;
     private String rgender;
     private String fname;
     private String rposition;
     private String rpwd;
     private String rstatus;
     private String rreason;

    public Recruiter() {
    }

	
    public Recruiter(String rname, String rtel, String remail, Date rbirth, String rgender, String fname, String rposition, String rpwd) {
        this.rname = rname;
        this.rtel = rtel;
        this.remail = remail;
        this.rbirth = rbirth;
        this.rgender = rgender;
        this.fname = fname;
        this.rposition = rposition;
        this.rpwd = rpwd;
    }
    public Recruiter(String rname, String rpic, String rtel, String remail, Date rbirth, String rgender, String fname, String rposition, String rpwd, String rstatus, String rreason) {
       this.rname = rname;
       this.rpic = rpic;
       this.rtel = rtel;
       this.remail = remail;
       this.rbirth = rbirth;
       this.rgender = rgender;
       this.fname = fname;
       this.rposition = rposition;
       this.rpwd = rpwd;
       this.rstatus = rstatus;
       this.rreason = rreason;
    }
   
    public String getRname() {
        return this.rname;
    }
    
    public void setRname(String rname) {
        this.rname = rname;
    }
    public String getRpic() {
        return this.rpic;
    }
    
    public void setRpic(String rpic) {
        this.rpic = rpic;
    }
    public String getRtel() {
        return this.rtel;
    }
    
    public void setRtel(String rtel) {
        this.rtel = rtel;
    }
    public String getRemail() {
        return this.remail;
    }
    
    public void setRemail(String remail) {
        this.remail = remail;
    }
    public Date getRbirth() {
        return this.rbirth;
    }
    
    public void setRbirth(Date rbirth) {
        this.rbirth = rbirth;
    }
    public String getRgender() {
        return this.rgender;
    }
    
    public void setRgender(String rgender) {
        this.rgender = rgender;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getRposition() {
        return this.rposition;
    }
    
    public void setRposition(String rposition) {
        this.rposition = rposition;
    }
    public String getRpwd() {
        return this.rpwd;
    }
    
    public void setRpwd(String rpwd) {
        this.rpwd = rpwd;
    }
    public String getRstatus() {
        return this.rstatus;
    }
    
    public void setRstatus(String rstatus) {
        this.rstatus = rstatus;
    }
    public String getRreason() {
        return this.rreason;
    }
    
    public void setRreason(String rreason) {
        this.rreason = rreason;
    }




}


